# -*- coding: utf-8 -*-
"""Sushmita & python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3DSmaOQSdao6jwMLFbMAzANOU1fd_Bt
"""

# Take paragraph input
paragraph = input("Enter a paragraph:\n")

# Count words
words = paragraph.split()
word_count = len(words)

# Count sentences (., ?, !)
sentence_endings = ['.', '?', '!']
sentence_count = 0
for ch in paragraph:
    if ch in sentence_endings:
        sentence_count += 1

print("\nWord count:", word_count)
print("Sentence count:", sentence_count)

# Replace a word
old_word = input("\nEnter the word you want to replace: ")
new_word = input("Enter the new word: ")

updated_paragraph = paragraph.replace(old_word, new_word)

print("\nUpdated paragraph:\n")
print(updated_paragraph)

"""
Tuple"""

# Creating and accessing a tuple
my_tuple = (10,20,30,"Python")
print("Original Tuple:", my_tuple)

# Accessing elements
print("First Element:", my_tuple[0])
print("Last Element:", my_tuple[-1])

# Tuple slicing
print("First Two Elements:",my_tuple[:2])

"""Set"""

# Creating and modifying a set
my_set = {10,20,30,40,10,20,30,40,}
print("Original Set:", my_set)

# Adding and removing elements
my_set.add(100)
print("After Add:", my_set)

my_set.remove(40)
print("After Remove:", my_set)

# Set operations
another_set = {35,45,20, 10,65}
print("Union:", my_set.union(another_set))
print("Intersection:", my_set.intersection(another_set))

"""Dictionary"""

# Creating and accessing a dictionary
my_dict = {"name":"Alice","age": 25,"city":"New York"}
print("Original Dictionary:", my_dict)

# Accessing values
print("Name:",my_dict["name"])

# Adding and updating entries
my_dict["age"] = 28
my_dict["country"] = "USA"
print("Updated Dictionary:", my_dict)

# Removing an entry
my_dict.pop("city")
print("After Remove:", my_dict)

"""Iterate Loops & Conditionl Statements"""

# using s for loop to iterate over a list
numbers = [10,20,30,40,50,60,70,80,]
for num in numbers:
  print("Number:", num)

  # Using a while loop to calculatec the sum of a list
  index = 0
  total = 0
  while index < len(numbers):
       total += numbers[index]
       index += 1
  print("Total Sum:", total)

"""Dictionary"""

# Iterating over keys and values in a dictionary
student = {"name": "Alice", "age": 20, "grade": "A"}
for key, value in student.items():
  print(f"{key}: {value}")

"""If-else with list"""

# Checking if a specific value exists in a list
numbers = [10,20,30,40,50,]
if 34 in numbers:
     print("34 is in the list ")
else:
     print("34 is not in the list")

"""If-elif-else with a dictionary"""

# Categorizing student grade based on score
Score = 98
if Score >=90:
  grade = "A"
elif Score >=75:
  grade = "B"
else:
  grade ="C"
print("Grade:", grade)

"""If with set"""

# Chicking if a set is a subset of another set
set1 = {1,2,9,4,}
set2 = {1,2,3,4,5,6,7,8,}
if set1.issubset(set2):
    print("set1 is a subset of set2")
else:
    print("set1 is not a subset of set2")

"""**Student** **Management**"""

# Student Management System
# Initializing data structures
students = [] # List to store student dictionaries

# Adding students
student1 = {"name": "Narayan", "age": 7, "grades":[56,78,90,]}
student2 = {"name": "Kartik", "age": 5, "grades":[78,90,68]}
students.append(student1)
students.append(student2)

#Display all students
print("List of student:")
for student in students:
    print(f"Name:{student['name']}, Age:{student['age']},Greads:")

    # Retrieve a speecific student's information
    name_to_find ="Narayan"
    for student in students:
        if student["name"] == name_to_find:
            print(f"\nInformation for {name_to_find}:")
            print(f"Age: {student['age']}")
            print(f"Grades: {student['grades']}")

    # Calculate the average grade of a student
    grades = student1["grades"]
    average_grade = sum(grades) / len(grades)
    print(f"\nAverage Grade for{student1['name']}: {average_grade:.2f}")