# -*- coding: utf-8 -*-
"""Sushmita & python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3DSmaOQSdao6jwMLFbMAzANOU1fd_Bt
"""

# Take paragraph input
paragraph = input("Enter a paragraph:\n")

# Count words
words = paragraph.split()
word_count = len(words)

# Count sentences (., ?, !)
sentence_endings = ['.', '?', '!']
sentence_count = 0
for ch in paragraph:
    if ch in sentence_endings:
        sentence_count += 1

print("\nWord count:", word_count)
print("Sentence count:", sentence_count)

# Replace a word
old_word = input("\nEnter the word you want to replace: ")
new_word = input("Enter the new word: ")

updated_paragraph = paragraph.replace(old_word, new_word)

print("\nUpdated paragraph:\n")
print(updated_paragraph)

"""
Tuple"""

# Creating and accessing a tuple
my_tuple = (10,20,30,"Python")
print("Original Tuple:", my_tuple)

# Accessing elements
print("First Element:", my_tuple[0])
print("Last Element:", my_tuple[-1])

# Tuple slicing
print("First Two Elements:",my_tuple[:2])

"""Set"""

# Creating and modifying a set
my_set = {10,20,30,40,10,20,30,40,}
print("Original Set:", my_set)

# Adding and removing elements
my_set.add(100)
print("After Add:", my_set)

my_set.remove(40)
print("After Remove:", my_set)

# Set operations
another_set = {35,45,20, 10,65}
print("Union:", my_set.union(another_set))
print("Intersection:", my_set.intersection(another_set))

"""Dictionary"""

# Creating and accessing a dictionary
my_dict = {"name":"Alice","age": 25,"city":"New York"}
print("Original Dictionary:", my_dict)

# Accessing values
print("Name:",my_dict["name"])

# Adding and updating entries
my_dict["age"] = 28
my_dict["country"] = "USA"
print("Updated Dictionary:", my_dict)

# Removing an entry
my_dict.pop("city")
print("After Remove:", my_dict)

"""Iterate Loops & Conditionl Statements"""

# using s for loop to iterate over a list
numbers = [10,20,30,40,50,60,70,80,]
for num in numbers:
  print("Number:", num)

  # Using a while loop to calculatec the sum of a list
  index = 0
  total = 0
  while index < len(numbers):
       total += numbers[index]
       index += 1
  print("Total Sum:", total)

"""Dictionary"""

# Iterating over keys and values in a dictionary
student = {"name": "Alice", "age": 20, "grade": "A"}
for key, value in student.items():
  print(f"{key}: {value}")

"""If-else with list"""

# Checking if a specific value exists in a list
numbers = [10,20,30,40,50,]
if 34 in numbers:
     print("34 is in the list ")
else:
     print("34 is not in the list")

"""If-elif-else with a dictionary"""

# Categorizing student grade based on score
Score = 98
if Score >=90:
  grade = "A"
elif Score >=75:
  grade = "B"
else:
  grade ="C"
print("Grade:", grade)

"""If with set"""

# Chicking if a set is a subset of another set
set1 = {1,2,9,4,}
set2 = {1,2,3,4,5,6,7,8,}
if set1.issubset(set2):
    print("set1 is a subset of set2")
else:
    print("set1 is not a subset of set2")

"""**Student** **Management**"""

# Student Management System
# Initializing data structures
students = [] # List to store student dictionaries

# Adding students
student1 = {"name": "Narayan", "age": 7, "grades":[56,78,90,]}
student2 = {"name": "Kartik", "age": 5, "grades":[78,90,68]}
students.append(student1)
students.append(student2)

#Display all students
print("List of student:")
for student in students:
    print(f"Name:{student['name']}, Age:{student['age']},Greads:")

    # Retrieve a speecific student's information
    name_to_find ="Narayan"
    for student in students:
        if student["name"] == name_to_find:
            print(f"\nInformation for {name_to_find}:")
            print(f"Age: {student['age']}")
            print(f"Grades: {student['grades']}")

    # Calculate the average grade of a student
    grades = student1["grades"]
    average_grade = sum(grades) / len(grades)
    print(f"\nAverage Grade for{student1['name']}: {average_grade:.2f}")

arr = [1, 2, 3, 4]

left = 0
right = len(arr) - 1

while left < right:
    arr[left], arr[right] = arr[right], arr[left]
    left += 1
    right -= 1

print(arr)

arr = [3, 7, 2, -93, 5]

max_val = arr[0]

for num in arr:
    if num > max_val:
        max_val = num

print(max_val)

s = "madam"

# Convert the string to lowercase to ignore case sensitivity
if s.lower() == s.lower()[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

arr = [1, 4, 6, 8]
target = 5

found = False

for num in arr:
    if num == target:
        found = True
        break

print("Found" if found else "Not Found")

# DSA stands for Data Structures and Algorithms.
# It involves organizing and storing data efficiently (Data Structures)
# and developing step-by-step procedures to solve problems (Algorithms).

arr = [1, 2, 3, 4, 6]

count = 0

for num in arr:
    if num % 2 == 0:
        count += 1

print(count)

n = 5

a, b = 0, 1

for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b

"""## Tree Data Structure Example: Binary Search Tree

A **Tree** is a hierarchical data structure consisting of nodes connected by edges. A **Binary Tree** is a tree data structure in which each node has at most two children, which are referred to as the left child and the right child.

A **Binary Search Tree (BST)** is a special type of binary tree where for each node:
- The value of all nodes in its left subtree is less than the node's value.
- The value of all nodes in its right subtree is greater than the node's value.
"""

class TreeNode:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

class BinarySearchTree:
    def __init__(self):
        self.root = None

    def insert(self, value):
        if self.root is None:
            self.root = TreeNode(value)
        else:
            self._insert_recursive(self.root, value)

    def _insert_recursive(self, node, value):
        if value < node.value:
            if node.left is None:
                node.left = TreeNode(value)
            else:
                self._insert_recursive(node.left, value)
        elif value > node.value:
            if node.right is None:
                node.right = TreeNode(value)
            else:
                self._insert_recursive(node.right, value)
        # If value is equal, we typically don't insert duplicates in a simple BST

    def inorder_traversal(self):
        elements = []
        self._inorder_recursive(self.root, elements)
        return elements

    def _inorder_recursive(self, node, elements):
        if node:
            self._inorder_recursive(node.left, elements)
            elements.append(node.value)
            self._inorder_recursive(node.right, elements)

"""### Demonstration of the Binary Search Tree"""

# Create a Binary Search Tree instance
bst = BinarySearchTree()

# Insert elements
bst.insert(50)
bst.insert(30)
bst.insert(70)
bst.insert(20)
bst.insert(40)
bst.insert(60)
bst.insert(80)
bst.insert(25) # Inserting a new value to show the tree growth

print("Elements in the BST (Inorder Traversal - should be sorted):")
print(bst.inorder_traversal())

"""# Object-Oriented Programming (OOP) Concepts

Object-Oriented Programming (OOP) is a programming paradigm based on the concept of "objects", which can contain data and code: data in the form of fields (often known as attributes or properties), and code in the form of procedures (often known as methods).

**Key Principles of OOP:**
1.  **Encapsulation:** Bundling data and methods that operate on the data within a single unit or class.
2.  **Inheritance:** A mechanism where a new class inherits properties and behaviors from an existing class.
3.  **Polymorphism:** The ability of an object to take on many forms. It allows objects of different classes to be treated as objects of a common base class.
4.  **Abstraction:** Hiding the complex implementation details and showing only the essential features of the object.

## 1. Encapsulation

**Definition:** Encapsulation is the bundling of data (attributes) and methods (functions) that operate on the data into a single unit, i.e., a class. It also restricts direct access to some of an object's components, which can prevent accidental modification of data. This is often achieved using access modifiers (like `private` or `protected` in some languages, or conventions like leading underscores in Python).

**Example:** Let's create a `Bank_Account` class where the balance is encapsulated.
"""

class Bank_Account:
    def __init__(self, account_holder, initial_balance=0):
        self.account_holder = account_holder
        self.__balance = initial_balance  # Private attribute (by convention)

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited ${amount}. New balance: ${self.__balance}")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        if amount > 0 and self.__balance >= amount:
            self.__balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.__balance}")
        elif amount <= 0:
            print("Withdrawal amount must be positive.")
        else:
            print("Insufficient balance.")

    def get_balance(self):
        return self.__balance

# Demonstration
my_account = Bank_Account("Sushmita Poddar", 1000)
print(f"Account holder: {my_account.account_holder}")
print(f"Initial balance: ${my_account.get_balance()}")

my_account.deposit(500)
my_account.withdraw(200)
my_account.withdraw(2000) # This will fail due to insufficient balance

# Attempting to access __balance directly (not recommended and technically still possible in Python)
# print(my_account.__balance) # This would raise an AttributeError
print(f"Final balance: ${my_account.get_balance()}")

"""## 2. Inheritance

**Definition:** Inheritance allows a class (child/subclass) to inherit attributes and methods from another class (parent/superclass). This promotes code reusability and establishes a natural hierarchy between classes.

**Example:** Let's create a `Vehicle` class and then `Car` and `Motorcycle` classes that inherit from `Vehicle`.
"""

class Vehicle:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def display_info(self):
        print(f"Vehicle: {self.year} {self.make} {self.model}")

    def start_engine(self):
        print(f"The {self.make} {self.model} engine starts.")

class Car(Vehicle):
    def __init__(self, make, model, year, num_doors):
        super().__init__(make, model, year) # Call parent constructor
        self.num_doors = num_doors

    def drive(self):
        print(f"The {self.make} {self.model} is driving with {self.num_doors} doors.")

class Motorcycle(Vehicle):
    def __init__(self, make, model, year, has_sidecar):
        super().__init__(make, model, year)
        self.has_sidecar = has_sidecar

    def wheelie(self):
        print(f"The {self.make} {self.model} is doing a wheelie!")

# Demonstration
my_car = Car("Toyota", "Camry", 2022, 4)
my_motorcycle = Motorcycle("Harley-Davidson", "Iron 883", 2021, False)

my_car.display_info()
my_car.start_engine()
my_car.drive()

print("\n")

my_motorcycle.display_info()
my_motorcycle.start_engine()
my_motorcycle.wheelie()

"""## 3. Polymorphism

**Definition:** Polymorphism means "many forms". In OOP, it refers to the ability of different classes to be treated as instances of a common base class. This allows a single interface to be used for different data types, leading to more flexible and reusable code. Polymorphism can be achieved through method overriding (runtime polymorphism) or method overloading (compile-time polymorphism - less explicit in Python).

**Example:** Using the `Vehicle` hierarchy, we can demonstrate polymorphism by calling a common method on different vehicle types.
"""

class Animal:
    def make_sound(self):
        raise NotImplementedError("Subclass must implement abstract method")

class Dog(Animal):
    def make_sound(self):
        return "Woof!"

class Cat(Animal):
    def make_sound(self):
        return "Meow!"

class Duck(Animal):
    def make_sound(self):
        return "Quack!"

# A function that can accept any Animal object
def animal_speak(animal):
    print(animal.make_sound())

# Demonstration
my_dog = Dog()
my_cat = Cat()
my_duck = Duck()

animals = [my_dog, my_cat, my_duck]

for animal in animals:
    animal_speak(animal)

"""## 4. Abstraction

**Definition:** Abstraction is the process of hiding the complex implementation details and showing only the essential features of an object. It focuses on *what* an object does rather than *how* it does it. In Python, abstraction can be achieved using Abstract Base Classes (ABCs) from the `abc` module.

**Example:** Let's define an abstract `Shape` class with an abstract method `area()`. Concrete shapes like `Circle` and `Rectangle` will then implement this method.
"""

from abc import ABC, abstractmethod
import math

class Shape(ABC): # Inherit from ABC to make it an abstract class
    @abstractmethod
    def area(self):
        pass # Abstract method, must be implemented by subclasses

    @abstractmethod
    def perimeter(self):
        pass # Another abstract method

    def display_color(self):
        print("This shape has a color.")

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius**2

    def perimeter(self):
        return 2 * math.pi * self.radius

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

    def perimeter(self):
        return 2 * (self.width + self.height)

# Demonstration
my_circle = Circle(5)
my_rectangle = Rectangle(4, 6)

print(f"Circle Area: {my_circle.area():.2f}")
print(f"Circle Perimeter: {my_circle.perimeter():.2f}")
my_circle.display_color() # Can use non-abstract method from base class

print("\n")

print(f"Rectangle Area: {my_rectangle.area()}")
print(f"Rectangle Perimeter: {my_rectangle.perimeter()}")
my_rectangle.display_color()

# Uncommenting the following line would raise a TypeError because Shape cannot be instantiated
# abstract_shape = Shape()

"""## Question & Answer Solution

Here are some common questions about OOP with concise answers:

**Q1: What is a Class in OOP?**
A1: A class is a blueprint or a template for creating objects (instances). It defines the attributes (data) and methods (behavior) that all objects of that class will have.

**Q2: What is an Object in OOP?**
A2: An object is an instance of a class. It's a real-world entity that has a state (attributes) and behavior (methods).

**Q3: What is the purpose of `__init__` in Python classes?**
A3: `__init__` is a special method called the constructor. It's automatically invoked when a new object of a class is created. Its primary purpose is to initialize the object's attributes.

**Q4: What is the difference between Encapsulation and Abstraction?**
A4: **Encapsulation** is about bundling data and methods within a single unit and controlling access to that data (data hiding). **Abstraction** is about hiding complex implementation details and showing only the essential features, focusing on *what* an object does rather than *how*.

**Q5: Can a class inherit from multiple classes in Python?**
A5: Yes, Python supports multiple inheritance, meaning a class can inherit from more than one parent class.

**Q6: What is Method Overriding?**
A6: Method overriding occurs when a subclass provides its own specific implementation for a method that is already defined in its superclass. This is a form of polymorphism.

**Q7: How is data typically "hidden" or made "private" in Python for encapsulation?**
A7: Python does not have strict `private` keywords like some other languages. By convention, a single leading underscore (`_variable`) indicates a protected attribute, and a double leading underscore (`__variable`) indicates a name-mangled attribute, making it harder (but not impossible) to access directly from outside the class. This serves as a strong hint to developers not to access them directly.
"""